name: Hokii Bot Auto

on:
  schedule:
    - cron: '15 17-23 * * *'  # WIB 00:30 - 06:30
    - cron: '15 0-16 * * *'   # WIB 07:30 - 23:30
  workflow_dispatch:

jobs:
  run-hokii:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium

      - name: Jalankan Bot
        run: |
          echo "üìÖ UTC Time  : $(date -u '+%Y-%m-%d %H:%M:%S')"
          echo "‚è∞ WIB Time  : $(TZ='Asia/Jakarta' date '+%Y-%m-%d %H:%M:%S')"
          output=$(python hokii.py)
          echo "$output"
          if echo "$output" | grep -q "‚úÖ Bettingan berhasil dikirim."; then
            echo "‚úÖ Workflow sukses"
            exit 0
          else
            echo "‚ùå Workflow gagal"
            exit 1
          fi
        env:
          userid: ${{ secrets.USERID }}
          pw: ${{ secrets.PW }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
